### ISSUE TITLE
TypeError when the observe proxy tries to access a symbol type property

### ISSUE THREAD

**Issue by baechul** [frankthelen/rools#32]
When the premises or action function contains "console.log(facts)" where facts is a just plain hash object, I got this error: 

```
TypeError: Cannot convert a Symbol value to a string
    at Delegator.delegator.set [as to] (/Users/xxx/war/repos/xxx/node_modules/rools/src/Rools.js:95:61)
    at Delegator.delegate (/Users/xxx/war/repos/xxx/node_modules/rools/src/Delegator.js:7:27)
    at segment (/Users/xxx/war/repos/xxx/node_modules/rools/src/Rools.js:28:55)
    at Object.get (/Users/xxx/war/repos/xxx/node_modules/rools/src/observe.js:4:7)
    at formatValue (util.js:450:28)
    at inspect (util.js:327:10)
    at Object.formatWithOptions (util.js:181:12)
    at Console.(anonymous function) (console.js:188:15)
    at Console.log (console.js:199:31)
    at _callee$ (/Users/xxx/war/repos/xxx/packages/api/test/specs/resources/rules/rules1.js:29:13)
```
This happened at https://github.com/frankthelen/rools/blob/master/src/Rools.js#L95. In this case, the segment was a symbol and can't be converted to a string automatically. In this case, explicit toString() should be called onto the symbol.

**Comment by frankthelen** [comment]
fixed and merged
